### ISSUE TITLE
Inject KeyEvent并不是完全模拟硬件按键按下

### ISSUE THREAD

**Issue by WuDi-ZhanShen** [ryuunoakaihitomi/PowerKeyAction#1]
UHid或者UInput才能真实模拟硬件按钮，你这个只是Java层模拟而已。我可以在代码中通过追溯你发的此次KeyEvent的源设备并检查源设备是否枚举出了自己支持此按键，从而查出此次的KeyEvent是假的。

或者我直接从InputDevice那边获取输入事件，这样你Inject的KeyEvent完全不会被我收到。

UHid和UInput都只需adb权限即可使用，可以参考我的陀螺仪MC源代码

**Comment by ryuunoakaihitomi** [comment]
学习了。

不过我现在这样也能用，所以暂时这样吧。
