### ISSUE TITLE
可以试试发送KEYCODE_SLEEP按键

### ISSUE THREAD

**Issue by WuDi-ZhanShen** [ryuunoakaihitomi/PowerKeyAction#2]
KEYCODE_SLEEP按键只会息屏而不会亮屏。对应地，只会亮屏而不会息屏的按键是KEYCODE_WAKEUP。

还有一个只会息屏而不会亮屏的按键叫SOFT_SLEEP键，其作用是模拟设备因为长时间不操作而自动息屏。但如果在设置开启了永不息屏，这个按键就失效了，因为此时设备再怎么长时间不操作也不会息屏。

**Comment by ryuunoakaihitomi** [comment]
marked
